language: node_js
script:
  - npm run test -- --env ci

before_install:
  # fire up xvfb on port :99.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  # install meteor
  - "curl https://install.meteor.com | /bin/sh"
  # setup Meteor app
  - "cd app; meteor reset; meteor -p 3000 &"
  - "cd .."
  # give Meteor some time to start
  - "sleep 5"